### ISSUE TITLE
Cannot read property 'slots' of undefined

### ISSUE THREAD

**Issue by martylietz** [alexa-js/alexa-app#287]
I am trying to get a session attribute to get a users name. but when I call it, it cannot read properly 'slots' of undefined. 

Here is my log output: 
START RequestId: dfee5395-a082-11e7-862e-6f05b61c62c7 Version: $LATEST
2017-09-23T17:16:03.550Z	dfee5395-a082-11e7-862e-6f05b61c62c7	Warning: Application ID is not set
2017-09-23T17:16:04.509Z	dfee5395-a082-11e7-862e-6f05b61c62c7	TypeError: Cannot read property 'slots' of undefined
    at Object.RemebmberNameIntent (/var/task/index.js:27:57)
    at emitNone (events.js:86:13)
    at AlexaRequestEmitter.emit (events.js:185:7)
    at Object.LaunchRequest (/var/task/index.js:22:10)
    at emitNone (events.js:86:13)
    at AlexaRequestEmitter.emit (events.js:185:7)
    at AlexaRequestEmitter.EmitEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:216:10)
    at ValidateRequest.attributesHelper.get (/var/task/node_modules/alexa-sdk/lib/alexa.js:170:27)
    at Response.<anonymous> (/var/task/node_modules/alexa-sdk/lib/DynamoAttributesHelper.js:43:25)
    at Request.<anonymous> (/var/task/node_modules/alexa-sdk/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/var/task/node_modules/alexa-sdk/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/task/node_modules/alexa-sdk/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/task/node_modules/alexa-sdk/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/task/node_modules/alexa-sdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/task/node_modules/alexa-sdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/task/node_modules/alexa-sdk/node_modules/aws-sdk/lib/state_machine.js:26:10
END RequestId: dfee5395-a082-11e7-862e-6f05b61c62c7
REPORT RequestId: dfee5395-a082-11e7-862e-6f05b61c62c7	Duration: 1094.07 ms	Billed Duration: 1100 ms 	Memory Size: 128 MB	Max Memory Used: 46 MB	
RequestId: dfee5395-a082-11e7-862e-6f05b61c62c7 Process exited before completing request

Here is the code when I am trying to ask for a name: 
'RemebmberNameIntent': function ()
  {
    this.atttributes['name'] = this.event.request.intent.slots.name.value;
    this.emit(':ask', 'Hi! Welcome to Welcoming Alarm! What is your name?');
    if (event.request.intent.slots.name !== undefined)
    {
      this.emit(':ask', "Sorry, I didnt get that, could you please repeat your name?")
    };
  },

**Comment by martylietz** [comment]
The rest of my code in is my git

**Comment by lazerwalker** [comment]
Hi! 

It looks like you're using the official Amazon-provided `alexa-sdk` npm module, rather than this third-party `alexa-js` project. You may have better luck asking for help in their repo/project page, at https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs.

Cheers!
