### ISSUE TITLE
intent.utterances.forEach is not a function

### ISSUE THREAD

**Issue by funkydan2** [alexa-js/alexa-app#323]
I've got a few skills using Alexa-App running on [Glitch](http://glitch.com).

For some projects, when I try to see the output from the ejs view engine I get the following error:

```
TypeError: intent.utterances.forEach is not a function
    at utterances (/rbd/pnpm-volume/82801dea-30b8-42f9-b5e7-3e7f0f22e4aa/node_modules/.registry.npmjs.org/alexa-app/4.2.1/node_modules/alexa-app/index.js:756:27)
    at /rbd/pnpm-volume/82801dea-30b8-42f9-b5e7-3e7f0f22e4aa/node_modules/.registry.npmjs.org/alexa-app/4.2.1/node_modules/alexa-app/index.js:829:32
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/82801dea-30b8-42f9-b5e7-3e7f0f22e4aa/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/layer.js:95:5)
    at next (/rbd/pnpm-volume/82801dea-30b8-42f9-b5e7-3e7f0f22e4aa/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/rbd/pnpm-volume/82801dea-30b8-42f9-b5e7-3e7f0f22e4aa/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/82801dea-30b8-42f9-b5e7-3e7f0f22e4aa/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/layer.js:95:5)
    at /rbd/pnpm-volume/82801dea-30b8-42f9-b5e7-3e7f0f22e4aa/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/rbd/pnpm-volume/82801dea-30b8-42f9-b5e7-3e7f0f22e4aa/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/index.js:335:12)
    at next (/rbd/pnpm-volume/82801dea-30b8-42f9-b5e7-3e7f0f22e4aa/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/rbd/pnpm-volume/82801dea-30b8-42f9-b5e7-3e7f0f22e4aa/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/82801dea-30b8-42f9-b5e7-3e7f0f22e4aa/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/rbd/pnpm-volume/82801dea-30b8-42f9-b5e7-3e7f0f22e4aa/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/index.js:317:13)
    at /rbd/pnpm-volume/82801dea-30b8-42f9-b5e7-3e7f0f22e4aa/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/rbd/pnpm-volume/82801dea-30b8-42f9-b5e7-3e7f0f22e4aa/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/index.js:335:12)
    at next (/rbd/pnpm-volume/82801dea-30b8-42f9-b5e7-3e7f0f22e4aa/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/router/index.js:275:10)
    at query (/rbd/pnpm-volume/82801dea-30b8-42f9-b5e7-3e7f0f22e4aa/node_modules/.registry.npmjs.org/express/4.16.3/node_modules/express/lib/middleware/query.js:45:5)
```

**Comment by funkydan2** [comment]
[Here's a code/project where the error is shown](https://qld-school-holidays.glitch.me).
[And here's one which doesn't give this error](https://gp-skill.glitch.me).

If you click **Show** you'll see either the error or the output from express.

**Comment by kobim** [comment]
Pay attention that `utterances` [might be null](https://github.com/alexa-js/alexa-app/blob/master/index.js#L310), and that's probably what generates this error.

I have to guess that your template does something like
```ejs
<% intent.utterances.forEach(function (utterance) { %>
  <%- utterance %>
<% }); %>
```
and you can resolve it by making sure there will be always an array to iterate on:
```ejs
<% (intent.utterances || []).forEach(function (utterance) { %>
  <%- utterance %>
<% }); %>
```

If this doesn't help, I would suggest you just print the utterances instead of looping them, just to make sure there are values there (`<%- intent.utterances %>` should be enough to debug).
You can also share a bit more code if you want us to better understand your problem.

**Comment by funkydan2** [comment]
Brilliant, thanks @kobim! There was an intent where I'd accidentally used curly brackets rather than square. Fixed now.
